---

- src: git+https://github.com/geerlingguy/ansible-role-git.git
  version: "1.2.1"
  name: geerlingguy.git

- src: git+https://github.com/geerlingguy/ansible-role-nginx.git
  version: "master"
  name: geerlingguy.nginx

- src: git+https://github.com/geerlingguy/ansible-role-mysql
  version: "2.8.0"
  name: geerlingguy.mysql
